---
- hosts: all
  become: true
  pre_tasks:
  - name: Update ubuntu repo
    tags: always
    apt:
      update_cache: yes
    when: ansible_distribution in ["Ubuntu", "Debian"]

- name: Local DNS setup across all the servers
  hosts: all
  become: true
  gather_facts: yes
  tags: base
  roles:
    - base

- hosts: all
  become: true
  tags: setup_openldap_server
  roles:
    - openldap_servers

- hosts: all
  become: true
  tags: setup_openldap_client
  roles:
    - openldap_clients

- hosts: all
  become: true
  tags: setup_lmod
  roles:
    - lmod